// lib/repository/quiz_repository.dart
import '../backend/api_client.dart';
import '../model/quiz_model.dart';

/// Quizzes and assignments. Grading and AI generation happen on the server;
/// errors surface as [ApiException] with a readable message.
class QuizRepository {
  final ApiClient _api = ApiClient.instance;

  /// The lesson's quiz. If none exists yet it is generated by the AI on the
  /// server (and saved, so every student gets the same questions).
  Future<QuizModel> getQuizForLesson({
    required String courseId,
    required String moduleId,
    required String lessonId,
    required String lessonTitle,
  }) async {
    try {
      return QuizModel.fromMap(await _api.json('GET', '/quizzes/lesson/$lessonId'));
    } on ApiException catch (e) {
      if (e.status != 404) rethrow;
    }
    final data = await _api.json('POST', '/ai/quiz',
        body: {'courseId': courseId, 'moduleId': moduleId, 'lessonId': lessonId, 'lessonTitle': lessonTitle},
        timeout: const Duration(seconds: 90));
    return QuizModel.fromMap(data);
  }

  /// Server grades the answers; returns the stored submission.
  Future<QuizSubmissionModel> submitQuiz(String quizId, Map<String, dynamic> answers, {int? timeSpent}) async {
    final data = await _api.json('POST', '/user/quizzes/$quizId/submit',
        body: {'answers': answers, 'timeSpent': timeSpent});
    return QuizSubmissionModel.fromMap(data);
  }

  Future<QuizSubmissionModel?> getQuizSubmission(String quizId) async {
    try {
      return QuizSubmissionModel.fromMap(await _api.json('GET', '/user/quizzes/$quizId/submission'));
    } on ApiException catch (e) {
      if (e.status == 404) return null;
      rethrow;
    }
  }

  Future<AssignmentModel?> getAssignmentForLesson(String lessonId) async {
    try {
      return AssignmentModel.fromMap(await _api.json('GET', '/assignments/lesson/$lessonId'));
    } on ApiException catch (e) {
      if (e.status == 404) return null;
      rethrow;
    }
  }

  /// Saves the work; the server asks the AI for feedback and a score. If the
  /// AI is unavailable the work is still saved, ungraded, and
  /// [AssignmentSubmissionModel.gradingNote] says why.
  Future<AssignmentSubmissionModel> submitAssignment(String assignmentId, {required String content, String? fileUrl}) async {
    final data = await _api.json('POST', '/user/assignments/$assignmentId/submit',
        body: {'content': content, 'fileUrl': fileUrl}, timeout: const Duration(seconds: 90));
    return AssignmentSubmissionModel.fromMap(data);
  }

  Future<AssignmentSubmissionModel?> getAssignmentSubmission(String assignmentId) async {
    try {
      return AssignmentSubmissionModel.fromMap(await _api.json('GET', '/user/assignments/$assignmentId/submission'));
    } on ApiException catch (e) {
      if (e.status == 404) return null;
      rethrow;
    }
  }

  /// Every assignment in the student's enrolled courses, each with
  /// `courseTitle`, `moduleTitle`, `lessonTitle` and `submission` (or null).
  Future<List<Map<String, dynamic>>> myAssignments() async =>
      ((await _api.json('GET', '/user/assignments')) as List).cast<Map<String, dynamic>>();

  // ── Admin authoring ──────────────────────────────────────────────────────
  Future<QuizModel> saveQuiz(QuizModel quiz) async => QuizModel.fromMap(await _api.json('POST', '/quizzes', body: quiz.toMap()));

  Future<AssignmentModel> saveAssignment(AssignmentModel a) async =>
      AssignmentModel.fromMap(await _api.json('POST', '/assignments', body: a.toMap()));
}
